### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by M2ck** [Tortel/SysLog#10]
Could you submit SysLog on F-Droid store please?

[Submission queue] (https://f-droid.org/forums/forum/submission-queue/)
[About F-Droid] (https://f-droid.org/about/)

**Comment by M2ck** [comment]
@Tortel [https://f-droid.org/forums/topic/syslog/](https://f-droid.org/forums/topic/syslog/)

**Comment by krt16s** [comment]
Should be building tomorrow.

**Comment by krt16s** [comment]
Problem is: v1.9.0 uses a depdency from jcenter which was removed by upstream (yeah, because f*rack existing users and builds...). HEAD is using newer versions from jitpack. I try to build with latest commit even this is not a release.. should be fixed with the next official version of SysLog.

**Comment by M2ck** [comment]
App available, thanks @krt16s!
