### ISSUE TITLE
[Request] audit log

### ISSUE THREAD

**Issue by Chainfire** [Tortel/SysLog#11]
`/data/misc/audit/audit.log`

On many devices this contains a log of SELinux audit failures that may not be present in logcat and/or dmesg output, and can be very handy to help diagnose issues related to security for root apps.

**Comment by Tortel** [comment]
This was included in version 1.9 and higher.

It uses cp to copy the file to the external storage, then chown's the files - if there are issues getting the logs it could be due to denials

**Comment by 8804645769** [comment]
Thanks

**Comment by curiousrom** [comment]
The Audit Logs option is now implemented so why not close the issue?

![screenshot_20181010-192428_syslog](https://user-images.githubusercontent.com/33857747/46857857-22277f80-cdc7-11e8-89b8-71ac87cac495.png)

**Comment by Tortel** [comment]
Heh, I forgot to
