### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 2.0.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [Tortel/SysLog#14]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 2.0.1.

**Comment by locutis-of-borg-1999** [comment]
I suppose anyone could do a oull request, but the dev'(s) know theur project, and it's links best and bear the brunt of the responsibility in upkeep/maintenance.

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog  

https://f-droid.org/repository/browse/?fdid=com.tortel.syslog

**Comment by Tortel** [comment]
I added a changelog file, I'm looking into how to add it to F-Droid

**Comment by Tortel** [comment]
Should be live soon: https://gitlab.com/fdroid/fdroiddata/merge_requests/1389
