### ISSUE TITLE
Cannot take log

### ISSUE THREAD

**Issue by nels83** [Tortel/SysLog#15]
I have a bug when I take log, directory is not created and logs are not saved.

I think the problem lies in Utils.java, you should use

` if(!outPath.mkdirs() || !outPath.isDirectory()){`

instead of

` if(!outPath.mkdirs() && !outPath.isDirectory()){`

Thanks for your very useful app.

**Comment by Tortel** [comment]
Thanks for the tip!
I'm working on re-writing how the logs are captured currently, it will take some time before it hits a release

**Comment by Tortel** [comment]
I just pushed 2.1.0 to Play, this fix is included.
