### ISSUE TITLE
Adapting SysLog into a service to run in background

### ISSUE THREAD

**Issue by diediaga** [Tortel/SysLog#18]
Hi

I'm working on adapting your sysLog code in to a simple app that launch a background services to collect the system log and send it back to the app and to remote server.
But I don't know where to collect the system log, I´m looking into the LiveLogActivity.class that inside has the LiveLogFragment (extend from Fragment) but they need an Activity to work... (onCreateView) 
I think the mTermSession is getting the data but again it works with and Activity...

so there is any simple way to get the log data from a services without need of an Activity?

thanks in advance.

**Comment by mercenaryship** [comment]
Where is your fork? Link it.

**Comment by diediaga** [comment]
it is here
https://github.com/diediaga/SysLog/tree/diediaga-patch-1
thanks

**Comment by mercenaryship** [comment]
I looked at the planned improvements of the fork and didn't see anything listed about  displaying the logs remotely for live monitoring, is the background service mainly required for cleanup and compression?

**Comment by Tortel** [comment]
This is the section that actually gets the logs and sends it to the UI:
https://github.com/Tortel/SysLog/blob/master/app/src/main/java/jackpal/androidterm/emulatorview/TermSession.java#L116

All you really need is a thread to get the logs and a handler to send them to the UI: https://developer.android.com/training/multiple-threads/communicate-ui.html

For a background service, you wont need to send anything to a UI, but maybe buffer it and send it in batches to the backend or a file or whatever

**Comment by diediaga** [comment]
Thanks very much
now is working very well. I just follow your instructions and I got it working.
regards
