### ISSUE TITLE
F-Droid version

### ISSUE THREAD

**Issue by protoloo** [Tortel/SysLog#20]
Hello. I saw that on F-Droid the app is "still" for some time, while on the Play Store there are other versions ... is it possible to update it?

**Comment by monteverde-org** [comment]
It's not Syslog's fault if F-Droid is currently 6 months behind in this case.

Quote from this page: https://f-droid.org/wiki/page/com.tortel.syslog

> We don't have the current version of this app. (Check mode: Tags) (Auto-update mode: Version v%v) 
The current (recommended) version is 2.1.1 (version code 25).

**Comment by Tortel** [comment]
The most recent version was disabled due to gradle version: https://gitlab.com/fdroid/fdroiddata/commit/794d9da3e38871e2a8c4b7f2626bbf874323c8d0

**Comment by Tortel** [comment]
I created a new release for F-Droid, so it now has the latest version
