### ISSUE TITLE
Add Proper Log's Name in the App Please

### ISSUE THREAD

**Issue by monteverde-org** [Tortel/SysLog#21]
I like to recommend Syslog in different forums to newbies because it makes sharing logs for troubleshooting so much easier for them but it's a pain to explain every time that Kernel log = dmesg, Last kernel log= last_kmsg, main log = logcat.

So why not add in parenthesis **in the app itself** the actual real log's name output like what you did in the [Syslog description in Google Play](https://play.google.com/store/apps/details?id=com.tortel.syslog&hl=en)?

> * Kernel logs (dmsg)
    * Last kernel log (last_kmsg, if device supports it)
    * Main log (Logcat)

Suggestion in red in the attachment:

![syslog_logs_real_name_note](https://user-images.githubusercontent.com/33857747/34669883-86c74f1e-f439-11e7-87cd-3096f236dc4d.png)

Anyway thank you for this awesome app & for keeping it up-to-date.

**Comment by Tortel** [comment]
Done in version 2.1.4
