### ISSUE TITLE
Syslog Play Store Description: ADB Permission Option for Non-root Devices Missing

### ISSUE THREAD

**Issue by curiousrom** [Tortel/SysLog#23]
Even more people could enjoy [Syslog](https://play.google.com/store/apps/details?id=com.tortel.syslog) if the app description in Play Store would include the adb set permission option.

This worked perfectly on un-rooted S5 Mini G800H & S5 G900M both running Android stock 6.0.1 and S5 G900M running LineageOS 15.1:

adb shell pm grant com.tortel.syslog android.permission.READ_LOGS

User review by Shahab Jafri in your Play page also mentions it.

You could check the example of [BetterBatteryStats](https://play.google.com/store/apps/details?id=com.asksven.betterbatterystats) > Unrooted devices chapter & it's [BBS unrooted devices FAQ page](http://better.asksven.org/nonroot-devices/) for inspiration.

Thanks for implementing the [issue 21](https://github.com/Tortel/SysLog/issues/21) suggestion.

_Edit:_ the screen captures also need to be updated. Current in Play page vs. Syslog 2.1.6:

![syslog_play_store](https://user-images.githubusercontent.com/33857747/46860285-543be000-cdcd-11e8-9d71-9e6417411a7b.png)

**Comment by Tortel** [comment]
Sorry this took so long - I just kept putting it off and forgetting about it.
Theres now info in the readme, Play description, and its also mentioned in the app.
I also just put up new screenshots
