### ISSUE TITLE
Error in the Readme.md & Better adb How-to Links Suggestion

### ISSUE THREAD

**Issue by curiousrom** [Tortel/SysLog#26]
In the current Readme.md seen in https://github.com/Tortel/SysLog it says:

> This is a simple application that records various log types, and compresses them, currently as a **tar** file.

But using Syslog current version v2.2.1 on LineageOS 16.0 and an older one on an other device running LineageOS 14.1 the files are compressed in the **.zip** format.

Below, still in the Read.md it says:

> There is a short guide on the Android developer site [here](https://developer.android.com/studio/run/device). More detailed guides can be found through a quick online search.

The problem with that [Android developer site page](https://developer.android.com/studio/run/device) is that it is not very user friendly and talks about Android emulator, Firebase Test Lab, Android Studio etc.

May I suggest instead this page about adb in the XDA portal [What is ADB? How to Install ADB, Common Uses, and Advanced Tutorials](https://www.xda-developers.com/what-is-adb/) (for Windows, macOS or Linux)?
***

Additionally in the [Syslog Play Store page](https://play.google.com/store/apps/details?id=com.tortel.syslog) it says correctly:

>Root is required to grab all logs, but you can manually grant access to the main log (Logcat) through ADB:
>adb shell pm grant com.tortel.syslog android.permission.READ_LOGS

Why not add the same info in the [Syslog F-Droid page](https://f-droid.org/packages/com.tortel.syslog/)?

This said thank you for your continuous support & the Syslog v2.2.1 update (October 13, 2019). :)

**Comment by Tortel** [comment]
Finally cleaning up old emails, and I updated the Readme with some better information.
Also, I opened a PR to update FDroid - https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6866
