### ISSUE TITLE
unable to create folder

### ISSUE THREAD

**Issue by Srinoid** [Tortel/SysLog#27]
07-18 23:41:42.802  2751  2789 V SysLog  : Path: /data/storage/emulated/0/SysLog/SysLog/2019-07-18_23.41/
07-18 23:41:42.805  2751  2789 E SysLog  : Exception while getting logs
07-18 23:41:42.805  2751  2789 E SysLog  : com.tortel.syslog.exception.CreateFolderException
07-18 23:41:42.805  2751  2789 E SysLog  :      at com.tortel.syslog.utils.GrabLogThread.runCommand(GrabLogThread.java:134)
07-18 23:41:42.805  2751  2789 E SysLog  :      at com.tortel.syslog.utils.GrabLogThread.run(GrabLogThread.java:82)
07-18 23:41:42.805  2751  2789 E SysLog  :      at java.lang.Thread.run(Thread.java:764)
07-18 23:41:42.805  2751  2789 V SysLog  : Done grabbing logs

**Comment by Tortel** [comment]
Latest version no longer uses the external storage, so this should no longer be an issue
