### ISSUE TITLE
[Request] Read live logcat feature

### ISSUE THREAD

**Issue by ghost** [Tortel/SysLog#7]
Add an option "Read Log" for read directly log in app would be useful. 
Is it possible or difficult to implement?
Thanks in advance.

**Comment by Tortel** [comment]
I have a partial implementation of this, I just have some bugs to work out.
Right now it starts showing the logcat and then the logcat process just dies

Hopefully I can get this worked out soon

**Comment by Micks29** [comment]
Ok thanks for accept this request!

It's not hurry, take your time.
